# Generated by Django 3.2 on 2021-08-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='student_status',
            field=models.BooleanField(default=True),
        ),
    ]
