# Generated by Django 3.2 on 2021-09-01 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createclass',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createclass',
            name='sem',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_member', to='user.createclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_class', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('class_group', 'user')},
            },
        ),
        migrations.AddField(
            model_name='createclass',
            name='students',
            field=models.ManyToManyField(through='user.ClassMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
