# Generated by Django 3.2 on 2021-09-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_marks_markslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markslist',
            name='date',
        ),
    ]
